spring.application.name=vitallyexercise

# SQL Server Configuration

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=vitallyexercisedb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.passaword=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect.SQLServerDialect

# Informações

# spring.jpa.hibernate.ddl-auto=
# none: Banco de dadoes e tabelas devem ser criadas com antecendência
# update; Banco de dados deve ser criado com antecedência, tabelas podem ser criadas com antecendência, entretanto,
#      as tabelas serão atualizadas pelo código JPA ( model )
# create-drop: Banco de dados deve ser criado com antecedência, as tabelas são criadas automaticamente pelo codigo ( model )
#              entretanto, as tabelas,


